class Autogenerated {
  List<HistoryTrans>? data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <HistoryTrans>[];
      json['data'].forEach((v) {
        data!.add(new HistoryTrans.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class HistoryTrans {
  int? id;
  String? noTransaction;
  String? idUsers;
  String? idProduct;
  String? qty;
  String? price;
  String? totalPrice;
  int? createdBy;
  int? updatedBy;
  String? createdAt;
  Null? updatedAt;
  String? status;

  HistoryTrans(
      {this.id,
      this.noTransaction,
      this.idUsers,
      this.idProduct,
      this.qty,
      this.price,
      this.totalPrice,
      this.createdBy,
      this.updatedBy,
      this.createdAt,
      this.updatedAt,
      this.status});

  HistoryTrans.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    noTransaction = json['no_transaction'];
    idUsers = json['id_users'];
    idProduct = json['id_product'];
    qty = json['qty'];
    price = json['price'];
    totalPrice = json['total_price'];
    createdBy = json['created_by'];
    updatedBy = json['updated_by'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['no_transaction'] = this.noTransaction;
    data['id_users'] = this.idUsers;
    data['id_product'] = this.idProduct;
    data['qty'] = this.qty;
    data['price'] = this.price;
    data['total_price'] = this.totalPrice;
    data['created_by'] = this.createdBy;
    data['updated_by'] = this.updatedBy;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['status'] = this.status;
    return data;
  }
}
